# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.3'
gem 'bootsnap', require: false
gem 'dotenv-rails'
gem 'jwt'
gem 'mysql2', '>= 0.5.3'
gem 'pry'
gem 'puma', '>= 5.0'
gem 'rack-cors'
gem 'rails', '~> 7.1.5'
gem 'rest-client'
gem 'rubocop', require: false
gem 'tzinfo-data', platforms: %i[windows jruby]
group :development, :test do
  gem 'debug', platforms: %i[mri windows]
end

group :development do
end
